# Site settings
title: Upsilon Pi Epsilon - UC Berkeley
email: info (at) upe.berkeley.edu
description: >
  Upsilon Pi Epsilon is the first and only international honor society for the Computing Sciences. 
  The UC Berkeley chapter, launched in 1995, honors the top tier of Computer Science students on campus.
url: "https://upe.berkeley.edu" # base hostname & protocol

# Build settings
markdown: kramdown

permalink: pretty
